volumes:
  db:

networks:
  api_net:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - CONNECTION_STRING=Username=admin;Password=admin;Host=db;Port=5432;Database=default
    ports:
      - "5000:8080"
    networks:
      - api_net
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=default
    ports:
      - "5432:5432"
    networks:
      - api_net
    volumes:
      - db:/var/lib/postgresql/data
    